# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoSidebarNavigation\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model}
